### PR TITLE
Fix undefined variables

### LINKED ISSUE #12: Strict variables issue
I am having an issue using this module with `strict_variables` enabled.

```
Error: Evaluation Error: Unknown variable: 'sys::unzip::params::source'. at /home/josh/dotfiles/puppet/ext_modules/sys/manifests/unzip.pp:8:15
```

### PR DESCRIPTION
**Pull request by joshuaspence**
Fixes undefined variables which cause failures with `strict_variables`. Fixes #12.

### CODE REVIEW

**Comment by jonemo** [comment]
Thanks for reporting this @joshuaspence. I can see how this wouldn't work with `strict_variables` enabled. Is this a complete fix for the problem for this module, or are `unzip` and `wget` just the two classes you happen to be using. From a quick glance it looks like the same problem exists with the `curl` class.

**Comment by joshuaspence** [comment]
From memory, this resolved `strict_variables`... But I may have patched the `wget` module as well. I will check later.

**Comment by joshuaspence** [comment]
OK, now I understand what you mean... so yeah, I only use a subset of the manifests provided by this module. Specifically, I only use this module because it is a dependency of https://github.com/counsyl/puppet-packer.

**Comment by hdeadman** [comment]
Any reason not to accept this pull request even if it isn't a complete fix? Users of other parts of the module can submit their own pull requests if they are annoyed by the unknown variable warnings. Personally I only get the warnings on wget and unzip so this pull request would resolve those warnings.

**Comment by jdavisp3** [comment]
Makes sense @hdeadman, thanks for your contribution!

**Pull request merged**
